import * as stylex from '@stylexjs/stylex';
import { colors, fonts, fontSizes, spacing, weights, zIndex } from '@/styles/theme.stylex';

export const styles = stylex.create({
  header: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    height: '124px',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    paddingInline: spacing.md,
    backgroundColor: 'rgba(255, 255, 255, 0.92)',
    backdropFilter: 'blur(12px)',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: colors.borderSubtle,
    boxSizing: 'border-box',
    zIndex: zIndex.header || 100,
    overflow: 'hidden',
  },
  flowerLeft: {
    position: 'absolute',
    left: 0,
    bottom: 0,
    height: '100%',
    maxHeight: '124px',
    width: 'auto',
    objectFit: 'contain',
    pointerEvents: 'none',
    opacity: 0.85,
  },
  flowerRightWrap: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    height: '100%',
    maxHeight: '124px',
    pointerEvents: 'none',
    transform: 'scaleX(-1)', // Aplicamos el espejo en un div contenedor para no romper el layout
  },
  flowerRight: {
    height: '100%',
    width: 'auto',
    objectFit: 'contain',
    opacity: 0.85,
  },
  branding: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  },
  heading: {
    fontFamily: fonts.serif,
    fontSize: fontSizes.xl2,
    fontWeight: weights.bold,
    color: colors.textPrimary,
    margin: 0,
    lineHeight: 1.1,
    letterSpacing: '0.05em',
  },
  caption: {
    fontFamily: fonts.sans,
    fontSize: '10px',
    fontWeight: weights.medium,
    color: colors.textBrand,
    textTransform: 'uppercase',
    letterSpacing: '0.15em',
    marginTop: '2px',
    margin: 0,
  },
  searchWrap: {
    position: 'relative',
    width: '100%',
    maxWidth: '400px',
    marginTop: spacing.xs,
    zIndex: 1,
  },
  searchIcon: {
    position: 'absolute',
    left: spacing.sm,
    top: '50%',
    transform: 'translateY(-50%)',
    color: colors.textSecondary,
    pointerEvents: 'none',
  },
});